### ISSUE TITLE
Nightly doc CI failing for Fluent 22.2

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent-visualization#282]
The nightly doc CI is [failing](https://github.com/ansys/pyfluent-visualization/actions/runs/5190404454/jobs/9356786679#step:8:319) for Fluent 22.2 with the following error:
```
Unexpected failing examples:
/home/runner/work/pyfluent-visualization/pyfluent-visualization/examples/00-postprocessing/post_processing_exhaust_manifold.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/runner/work/pyfluent-visualization/pyfluent-visualization/examples/00-postprocessing/post_processing_exhaust_manifold.py", line 135, in <module>
    iso_surf1.iso_value = -0.125017
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/fluent/core/meta.py", line 480, in wrapper
    attr.set_state(value)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/fluent/core/meta.py", line 279, in wrapper
    self.value = self._validate(value) if validate else value
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/fluent/core/meta.py", line 196, in wrapper
    if self.range and (
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/fluent/core/meta.py", line 45, in __get__
    return self.function(obj)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/fluent/core/post_objects/post_object_definitions.py", line 347, in range
    return self._api_helper.field_info().get_scalar_fields_range(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/fluent/core/services/field_data.py", line 122, in get_scalar_fields_range
    response = self._service.get_scalar_fields_range(request)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ansys/fluent/core/services/error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: Cell_Function_Values: unrecognized function: y
Error Object: #f
```

**Comment by seanpearsonuk** [comment]
@ajain-work this is still failing and perhaps you are best equipped to analyse the situation.
